# Numpy Basics

Welcome to section of Numpy and Pandas. This is the most used Python libraries for data science. NumPy consists of a powerful data structure called multidimensional arrays. Pandas is another powerful Python library that provides fast and easy data analysis platform.

NumPy is a library written for scientific computing and data analysis. It stands for numerical python and also known as array oriented computing.

The most basic object in NumPy is the ndarray, or simply an array which is an n-dimensional, homogeneous array. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which is commonly numeric (float or integer).


 # Why Numpy?
 convenience & speed
 
 Numpy is much faster than the standard python ways to do computations.
 
Vectorised code typically does not contain explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

Also, many Numpy operations are implemented in C which is basically being executed behind the scenes, avoiding the general cost of loops in Python, pointer indirection and per-element dynamic type checking. The speed boost depends on which operations you're performing.
 
 NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists

In [1]:
import numpy

numpy.array([1,2,3])

array([1, 2, 3])

In [2]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [10]:
print(b.shape)
print(a.shape)


(2, 3)
(3,)


In [12]:
print(b.dtype)
print(b.ndim)
print(type(a))
print(type(b))
np.arange(10)

int32
2
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Performance measurement
I mentioned that the key advantages of numpy are convenience and speed of computation.

You'll often work with extremely large datasets, and thus it is important point for you to understand how much computation time (and memory) you can save using numpy, compared to standard python lists.

In [13]:
c = range(10000)
%timeit [i**3 for i in c]

4.1 ms ± 182 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
c_numpy = np.arange(10000)
%timeit c_numpy**3

21.5 µs ± 860 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Still not convinced? want to see one more intresting example

In [15]:
l1 = range(10000)
l2 = [i**2 for i in range(10000)]

In [16]:
%timeit list(map(lambda x, y: x*y, l1, l2))

1.7 ms ± 71.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
a1 = np.array(l1)
b1 = np.array(l2)

In [18]:
%timeit a1*b1

10.2 µs ± 304 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [19]:
a1

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [20]:
a1*a1

array([       0,        1,        4, ..., 99940009, 99960004, 99980001])

# Creating Numpy array

There are multiple ways to create numpy array. Lets walk over them

In [21]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [23]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [27]:
np.full((3,3),2.2, dtype= np.int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [28]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [29]:
v = np.array([1,2,3])
np.tile(v,(3,1)) # stack 3 copies of v on top of each other

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [30]:
# between 0 and 1
print(np.random.random())
# so let say I want a random value between 2 and 50
print(50*np.random.random()+2)

0.5178084568997262
4.578513909373248
